import React, { useEffect, useRef, useState } from 'react';

function cn(...classes: (string | boolean | undefined | null)[]) {
  return classes.filter(Boolean).join(' ');
}

const randomColors = (count: number) => {
  return new Array(count)
    .fill(0)
    .map(() => "#" + Math.floor(Math.random() * 16777215).toString(16).padStart(6, '0'));
};

interface TubesBackgroundProps {
  children?: React.ReactNode;
  className?: string;
  enableClickInteraction?: boolean;
  hoverOnly?: boolean;
  autoAnimate?: boolean;
  bgImage?: string;
  bgImageMobile?: string;
  bgOverlayClass?: string;
}

export function TubesBackground({ 
  children, 
  className,
  enableClickInteraction = true,
  hoverOnly = false,
  autoAnimate = true,
  bgImage,
  bgImageMobile,
  bgOverlayClass = "bg-black/35"
}: TubesBackgroundProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isHovered, setIsHovered] = useState(!hoverOnly);
  const tubesRef = useRef<any>(null);
  const userInteractedRef = useRef<boolean>(false);
  const userInteractionTimeoutRef = useRef<any>(null);
  const lastCursorPosRef = useRef<{ x: number; y: number }>({ x: window.innerWidth / 2, y: window.innerHeight / 2 });

  useEffect(() => {
    let mounted = true;
    let cleanup: (() => void) | undefined;
    let animFrameId: number;

    // Window level listener for pointer activity to detect idle state
    const handleGlobalPointerMove = (e: MouseEvent | PointerEvent) => {
      // Ignore synthetic events generated by auto-animation
      if (!e.isTrusted) return;

      lastCursorPosRef.current = { x: e.clientX, y: e.clientY };
      userInteractedRef.current = true;

      if (userInteractionTimeoutRef.current) {
        clearTimeout(userInteractionTimeoutRef.current);
      }

      // Resume auto animation after 1.8s of idle (no user mouse movement)
      userInteractionTimeoutRef.current = setTimeout(() => {
        userInteractedRef.current = false;
      }, 1800);
    };

    window.addEventListener('mousemove', handleGlobalPointerMove, { passive: true });
    window.addEventListener('pointermove', handleGlobalPointerMove, { passive: true });

    const initTubes = async () => {
      if (!canvasRef.current) return;

      try {
        // Dynamic import of ThreeJS components tubes cursor
        // @ts-ignore
        const module = await import(/* @vite-ignore */ 'https://cdn.jsdelivr.net/npm/threejs-components@0.0.19/build/cursors/tubes1.min.js');
        const TubesCursor = module.default;

        if (!mounted || !canvasRef.current) return;

        const app = TubesCursor(canvasRef.current, {
          tubes: {
            colors: ["#f967fb", "#53bc28", "#6958d5"],
            lights: {
              intensity: 200,
              colors: ["#83f36e", "#fe8a2e", "#ff008a", "#60aed5"]
            }
          }
        });

        tubesRef.current = app;

        // Make WebGL canvas background transparent so underlying images/backgrounds show through
        if (app.three) {
          if (app.three.renderer) {
            app.three.renderer.setClearColor(0x000000, 0);
          }
          if (app.three.scene) {
            app.three.scene.background = null;
          }
        }

        // Auto animation motion loop across all regions of the hero section
        if (autoAnimate) {
          // Landmark keys spanning top-left, top-right, center, bottom-left, bottom-right, and top-center
          type LandmarkKey = 'print' | 'top-right' | 'design' | 'bottom-left' | 'layout' | 'top-center';

          // Varied organic movement sequences covering all parts of the hero section
          const sequences: Array<LandmarkKey[]> = [
            ['print', 'top-right', 'design', 'bottom-left', 'layout', 'top-center'],
            ['top-center', 'print', 'design', 'top-right', 'layout', 'bottom-left'],
            ['design', 'bottom-left', 'print', 'top-center', 'layout', 'top-right'],
            ['layout', 'top-right', 'design', 'print', 'bottom-left', 'top-center'],
          ];

          let seqIdx = 0;
          let nodeIdx = 0;
          let progress = 0;
          let timeCounter = 0;
          const speed = 0.005; // Smooth, continuous gliding speed between hero regions

          const getPoint = (key: LandmarkKey) => {
            const containerRect = containerRef.current?.getBoundingClientRect();
            const w = (containerRect && containerRect.width > 0) ? containerRect.width : (window.innerWidth || 1000);
            const h = (containerRect && containerRect.height > 0) ? containerRect.height : (window.innerHeight || 800);
            const left = containerRect ? containerRect.left : 0;
            const top = containerRect ? containerRect.top : 0;

            if (key === 'print') {
              const el = document.getElementById('caption-print');
              if (el) {
                const rect = el.getBoundingClientRect();
                if (rect.width > 0 && rect.height > 0) {
                  return { x: rect.left + rect.width * 0.4, y: rect.top + rect.height * 0.5 };
                }
              }
              return { x: left + w * 0.2, y: top + h * 0.25 };
            }

            if (key === 'design') {
              const el = document.getElementById('caption-design');
              if (el) {
                const rect = el.getBoundingClientRect();
                if (rect.width > 0 && rect.height > 0) {
                  return { x: rect.left + rect.width * 0.45, y: rect.top + rect.height * 0.5 };
                }
              }
              return { x: left + w * 0.45, y: top + h * 0.5 };
            }

            if (key === 'layout') {
              const el = document.getElementById('caption-layout');
              if (el) {
                const rect = el.getBoundingClientRect();
                if (rect.width > 0 && rect.height > 0) {
                  return { x: rect.left + rect.width * 0.5, y: rect.top + rect.height * 0.5 };
                }
              }
              return { x: left + w * 0.75, y: top + h * 0.75 };
            }

            if (key === 'top-right') {
              return { x: left + w * 0.82, y: top + h * 0.22 };
            }

            if (key === 'bottom-left') {
              return { x: left + w * 0.18, y: top + h * 0.78 };
            }

            // 'top-center'
            return { x: left + w * 0.5, y: top + h * 0.15 };
          };

          const animateMotion = () => {
            if (mounted && containerRef.current && !userInteractedRef.current) {
              const containerRect = containerRef.current.getBoundingClientRect();
              if (containerRect.width > 0 && containerRect.height > 0) {
                progress += speed;
                timeCounter += 0.015;

                const currentSeq = sequences[seqIdx];
                const fromKey = currentSeq[nodeIdx];
                const toKey = currentSeq[(nodeIdx + 1) % currentSeq.length];

                if (progress >= 1) {
                  progress = 0;
                  nodeIdx++;
                  if (nodeIdx >= currentSeq.length) {
                    nodeIdx = 0;
                    seqIdx = (seqIdx + 1) % sequences.length;
                  }
                }

                const pA = getPoint(fromKey);
                const pB = getPoint(toKey);

                if (Number.isFinite(pA.x) && Number.isFinite(pA.y) && Number.isFinite(pB.x) && Number.isFinite(pB.y)) {
                  // Smooth quintic / cosine easing for dynamic fluid movement
                  const ease = 0.5 - 0.5 * Math.cos(progress * Math.PI);

                  // Organic multi-harmonic Lissajous offsets so neon flows in flowing curves rather than rigid lines
                  const archX = Math.sin(progress * Math.PI) * 70 + Math.sin(timeCounter * 1.4) * 30;
                  const archY = Math.cos(progress * Math.PI * 0.5) * 55 + Math.cos(timeCounter * 1.8) * 25;

                  const x = pA.x + (pB.x - pA.x) * ease + archX;
                  const y = pA.y + (pB.y - pA.y) * ease + archY;

                  if (Number.isFinite(x) && Number.isFinite(y)) {
                    // 1. Direct update to Three.js 3D world space target if available
                    if (tubesRef.current && tubesRef.current.tubes && tubesRef.current.tubes.target) {
                      const app = tubesRef.current;
                      if (app.three && app.three.size && app.three.size.width > 0) {
                        const wWidth = app.three.size.wWidth || 10;
                        const wHeight = app.three.size.wHeight || 6;

                        const nx = (x - containerRect.left) / containerRect.width - 0.5;
                        const ny = -((y - containerRect.top) / containerRect.height - 0.5);

                        if (Number.isFinite(nx) && Number.isFinite(ny) && Number.isFinite(wWidth) && Number.isFinite(wHeight)) {
                          app.tubes.target.x = nx * wWidth;
                          app.tubes.target.y = ny * wHeight;
                        }
                      }
                    }

                    // 2. Also update pointer coordinates on app if set method exposed
                    if (tubesRef.current) {
                      if (tubesRef.current.pointer && typeof tubesRef.current.pointer.set === 'function') {
                        tubesRef.current.pointer.set(x, y);
                      } else if (tubesRef.current.mouse && typeof tubesRef.current.mouse.set === 'function') {
                        tubesRef.current.mouse.set(x, y);
                      }
                    }

                    // 3. Dispatch synthetic pointer and mouse events
                    const eventProps: PointerEventInit = {
                      clientX: x,
                      clientY: y,
                      screenX: x,
                      screenY: y,
                      pointerId: 1,
                      pointerType: "mouse",
                      isPrimary: true,
                      bubbles: true,
                      cancelable: true,
                      view: window,
                    };

                    const pEvent = new PointerEvent("pointermove", eventProps);
                    const mEvent = new MouseEvent("mousemove", eventProps);

                    window.dispatchEvent(pEvent);
                    window.dispatchEvent(mEvent);
                    document.dispatchEvent(pEvent);
                    document.dispatchEvent(mEvent);

                    if (canvasRef.current) {
                      canvasRef.current.dispatchEvent(pEvent);
                      canvasRef.current.dispatchEvent(mEvent);
                    }
                  }
                }
              }
            }
            animFrameId = requestAnimationFrame(animateMotion);
          };
          animateMotion();
        }

        cleanup = () => {
          if (animFrameId) cancelAnimationFrame(animFrameId);
        };

      } catch (error) {
        console.error("Failed to load TubesCursor:", error);
      }
    };

    initTubes();

    return () => {
      mounted = false;
      window.removeEventListener('mousemove', handleGlobalPointerMove);
      window.removeEventListener('pointermove', handleGlobalPointerMove);
      if (userInteractionTimeoutRef.current) clearTimeout(userInteractionTimeoutRef.current);
      if (cleanup) cleanup();
    };
  }, [autoAnimate]);

  const handlePointerMove = (e: React.PointerEvent) => {
    if (!e.isTrusted) return;
    lastCursorPosRef.current = { x: e.clientX, y: e.clientY };
    userInteractedRef.current = true;
    if (userInteractionTimeoutRef.current) {
      clearTimeout(userInteractionTimeoutRef.current);
    }
    // Resume auto animation after 1.8 seconds of idle
    userInteractionTimeoutRef.current = setTimeout(() => {
      userInteractedRef.current = false;
    }, 1800);
  };

  const handleClick = () => {
    if (!enableClickInteraction || !tubesRef.current) return;
    
    const colors = randomColors(3);
    const lightsColors = randomColors(4);
    
    tubesRef.current.tubes.setColors(colors);
    tubesRef.current.tubes.setLightsColors(lightsColors);
  };

  return (
    <div 
      ref={containerRef}
      className={cn("relative w-full h-full min-h-screen overflow-hidden", !className?.includes('bg-') && "bg-[#0B1F18]", className)}
      onClick={handleClick}
      onPointerMove={handlePointerMove}
      onMouseEnter={() => hoverOnly && setIsHovered(true)}
      onMouseLeave={() => hoverOnly && setIsHovered(false)}
    >
      {(bgImage || bgImageMobile) && (
        <div className="absolute inset-0 w-full h-full pointer-events-none z-0">
          {bgImageMobile ? (
            <picture className="w-full h-full block">
              <source media="(max-width: 1023px)" srcSet={bgImageMobile} />
              <img 
                src={bgImage || bgImageMobile} 
                alt="Hero Background" 
                className="w-full h-full object-cover object-center"
                referrerPolicy="no-referrer"
              />
            </picture>
          ) : (
            <img 
              src={bgImage} 
              alt="Hero Background" 
              className="w-full h-full object-cover object-center"
              referrerPolicy="no-referrer"
            />
          )}
          {bgOverlayClass && <div className={cn("absolute inset-0", bgOverlayClass)} />}
        </div>
      )}

      <canvas 
        ref={canvasRef} 
        className={cn(
          "absolute inset-0 w-full h-full block transition-opacity duration-700 pointer-events-none z-0",
          hoverOnly && !isHovered ? "opacity-0" : "opacity-100"
        )}
        style={{ touchAction: 'none', mixBlendMode: 'screen' }}
      />
      
      {/* Content Overlay */}
      <div className="relative z-10 w-full h-full flex items-center justify-center pointer-events-none">
        {children}
      </div>
    </div>
  );
}

export default TubesBackground;
